export const LANGUAGE_COLORS: Record<string, string> = {
    javascript: '--yellow',
    python: '--blue',
    typescript: '--blue',
    java: '--orange',
    csharp: '--green',
    ruby: '--red',
    go: '--blue',
    php: '--blue',
    rust: '--orange',
    html: '--red',
    css: '--purple',
    swift: '--orange',
    graphql: '--pink',
    kotlin: '--orange',
    scss: '--pink',
    dart: '--cyan',
    lua: '--blue',
    sql: '--orange',
    bash: '--green',
    powershell: '--blue',
    r: '--blue',
    c: '--gray',
    cpp: '--pink',

}